### PR TITLE
Switched array() to []

### PR DESCRIPTION
**Pull request by Arman-Hosseini**

### CODE REVIEW

**Comment by lyrixx** [comment]
Hello, thanks for your contribution, but this script should be run on the lowest PHP version possible.

**Comment by Arman-Hosseini** [comment]
Hello @lyrixx, and thanks for review this.
Actually **Symfony 3.4 Standard Edition** requires PHP >= **5.5.9** and arrays with using definition [], works with PHP >= **5.4**

**Comment by bocharsky-bw** [comment]
Yes, but the point is to be able to check requirements on PHP version that might be even lower than 5.5.9, then you would get a message that your PHP version does not meet the required one. If we apply tour change - you will see just a fatal error.

**Comment by fabpot** [comment]
@bocharsky-bw is right.

**Pull request closed without merging**
