### PR TITLE
Remove extra empty line in config.yml

### PR DESCRIPTION
**Pull request by chalasr**

### CODE REVIEW

**Comment by ogizanagi** [comment]
I'm 👍  of course theoretically, but in practice I think @nervo wants to keep the minimum differences with upstream 😅 

But afterall... ¯\\_(ツ)_/¯

**Comment by stof** [comment]
@ogizanagi which upstream are you talking about ?

**Comment by ogizanagi** [comment]
@stof : NVM. It was a mistake 😛

**Comment by xabbuh** [comment]
:+1:

**Comment by stof** [comment]
Thank you @chalasr.

**Pull request closed without merging**
