### PR TITLE
Removing the symfony-tests-dir composer extra config - it's not used

### PR DESCRIPTION
**Pull request by weaverryan**
This was originally proposed for sensiolabs/SensioGeneratorBundle#416 (in #862), but I'm proposing to solve that in a simpler way: sensiolabs/SensioGeneratorBundle#494

Thanks!

### CODE REVIEW

**Comment by fabpot** [comment]
Why not use this configuration setting in #494?

**Comment by weaverryan** [comment]
@fabpot afaik, there is no way to read composer.json extra values at runtime (other than parsing the file manually). Plus, are we sure we want the extra `composer.json` key just to help an edge feature in the generator? Unless there are some other places where we might use that value in the future?

**Comment by Ener-Getick** [comment]
Is it worth removing it ? I can think of some use cases in third party library.

**Comment by fabpot** [comment]
Let's keep it, it does not hurt.

**Pull request closed without merging**
