### PR TITLE
[2.8] update composer dependencies

### PR DESCRIPTION
**Pull request by vincentaubert**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by vincentaubert** [comment]
link to issue  #806

**Comment by GrahamCampbell** [comment]
There's more than one fix in here. Shouldn't they be separated?

**Comment by vincentaubert** [comment]
The Symfony requirements file has been automatically updated by composer when I ran the composer update command. So I propose to add it

**Comment by GrahamCampbell** [comment]
Ok. :)

**Comment by Tobion** [comment]
This needs to be redone as I merged 2.7 upwards.

**Comment by vincentaubert** [comment]
done

**Comment by Tobion** [comment]
Please squash the commits into one.

**Comment by vincentaubert** [comment]
done

**Comment by lyrixx** [comment]
@Tobion Why don't you merge PR with GH ? it eases work of contributor, and also the work of people who write blog post about new features.

**Comment by fabpot** [comment]
I missed that but indeed, all merge must be done with GH.

**Comment by Tobion** [comment]
I didn't know I can use GH for PRs on symfony-standard. Will do so from now on.
Does GH support different naming of the "origin" remote by now? Otherwise I can the rename my remotes there as well :(

**Comment by stof** [comment]
@Tobion you can use it for any repo. 
And no, it only support ``origin`` (I was the only one interested in this feature at this time, and I changed my naming convention for remotes when changing computer, so I never completed the work on this). See the discussion on the GH repo.

**Pull request merged**
