### PR TITLE
use another method to provide more understandable content to getRootDir, ...

### PR DESCRIPTION
**Pull request by kmelia**
… getCacheDir and getLogDir

This is the proposition I made on the last comment of the closed PR #914 

It provide more understandable content to the ``get*Dir()`` methods.

### CODE REVIEW

**Comment by Tobion** [comment]
It adds 4 methods calls on every request for no reason. So I'm :-1:

**Comment by Tobion** [comment]
Btw, you can do these changes in your own AppKernel easily. This is just a template after all.

**Comment by kmelia** [comment]
> Btw, you can do these changes in your own AppKernel easily. This is just a template after all.

Yes of course, it was just the proposition I could not do in PR #914 ;)

**Comment by jakzal** [comment]
:-1: 

I agree with @Tobion. There's no benefit of doing this while we'd add method calls in a class that's used on every request.

**Pull request closed without merging**
