### PR TITLE
[2.6+] Removed AcmeDemoBundle

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

This removes the AcmeDemoBundle for Symfony Standard 2.6+.

### CODE REVIEW

**Comment by Pierstoval** [comment]
:+1: What about 2.7 also?

**Comment by javiereguiluz** [comment]
@Pierstoval 2.7 is included too. This PR is for any Symfony version higher than 2.6.

**Comment by GrahamCampbell** [comment]
This is not a bug fix, so surely it's not allowed into 2.6, and must go into 2.7+.

**Comment by fabpot** [comment]
@GrahamCampbell Symfony SE works in a different way than Symfony. The versions reflect the Symfony version for which SE is tied with. Nobody upgrades its Symfony SE, it's just a starting point for new projects.

**Comment by Tobion** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by weaverryan** [comment]
We're ready on the docs (a few spots still mention AcmeDemoBundle, but I don't think it's an issue). Can anyone think of any other side effects we haven't covered yet?

Regardless, :+1:

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Pull request merged**
