### PR TITLE
update Doctrine dependencies versions

### LINKED ISSUE #798: what's this? de_
version : 2.7
it's error when i run php app/console cache:clear . 
[2015-04-14 11:46:21] php.WARNING: unlink(/usr/local/var/www/symfony-standard-2.7/app/cache/`de_`/annotations/552c8d8d980d34.40127459qhMRLB): No such file or directory {"type":2,"file":"/usr/local/var/www/symfony-standard-2.7/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php","line":214,"level":4352}

i guess de_ is dev environment?

### PR DESCRIPTION
**Pull request by xabbuh**
This fixes #798 and symfony/symfony#14353.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Just did the same thing on my Symfony project, seems to works well now. :+1:

**Comment by fabpot** [comment]
Is it only a problem with 2.7? Don't we need to do the same on older branches?

**Comment by Pierstoval** [comment]
I personnally have this problem only with 2.7. Tested with 2 other apps, one on 2.6 and one on 2.5. Don't know about 2.3 :confused:

**Comment by xabbuh** [comment]
At least, I couldn't reproduce the issue on the other branches.

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
