### PR TITLE
remove references to Symfony2

### PR DESCRIPTION
**Pull request by ip512**
it's weird to have references to sf2 when installing sf3 project

### CODE REVIEW

**Comment by Pierstoval** [comment]
Duplicate of sooo many other PRs, it's solved in SensioDistributionBundle and will be fixed on the next release

**Comment by ip512** [comment]
I don't see any symfony_requirements file in SensioDistributionBundle but anyway, if you say it's fixed...

**Comment by Pierstoval** [comment]
The file is [here](https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/skeleton/app/SymfonyRequirements.php) and the zip files that one downloads from the website are generated by [this script](https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/bin/build.sh) which is executed server-side by SensioLabs

**Comment by ip512** [comment]
indeed, thanks for the information!

**Pull request closed without merging**
