### PR TITLE
merged the two php tags in phpunit config file into one

### PR DESCRIPTION
**Pull request by tifabien**

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by Pierstoval** [comment]
:+1:

**Comment by WouterJ** [comment]
:+1:

**Comment by Tobion** [comment]
This should be changed in 2.3: https://github.com/symfony/symfony-standard/blob/2.3/app/phpunit.xml.dist#L24

**Comment by fabpot** [comment]
As the fix is different in 2.3, I've made the change in ea679b0 and merge it up to all other branches. Thanks.

**Pull request closed without merging**
