### PR TITLE
Add note about permissions setup in app.php

### PR DESCRIPTION
**Pull request by bocharsky-bw**
We already have this for `app_dev.php`

### CODE REVIEW

**Comment by jakzal** [comment]
Don't you think that permissions should be set up the "proper way" on prod?

**Comment by bocharsky-bw** [comment]
Of course, if it possible. There's a link in that comment which refers to the docs where pointed some info about setup permissions in the proper way.

**Comment by jakzal** [comment]
Anyway, I find it messy to have this comment in there. It could be it's justified to have it in the dev controller to make things easier for newcomers. I wouldn't add it to the prod one though.

**Comment by fabpot** [comment]
I agree with @jakzal, it does not make sense to "promote" a bad practice in the production controller.

**Pull request closed without merging**
