### PR TITLE
Use proper autoloading for the kernel rather than file inclusion

### PR DESCRIPTION
**Pull request by stof**
This allows to register the autoloading for AppCache too, making the diff smaller when wanting to use it.

### CODE REVIEW

**Comment by Pierstoval** [comment]
Very :+1:

**Comment by stof** [comment]
sorry to have missed it before the release. I noticed files was used instead of classmap while looking at the KnpUniversity screencast about upgrading a project.

**Comment by Tobion** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by weaverryan** [comment]
Makes sense to me. @stof is this just a "nice" thing, or are there some real consequences related to autoloading (related to your conversation on symfony/symfony-installer#213)?

**Comment by stof** [comment]
There is a consequence: the AppKernel class is not loaded as soon as you load the composer ClassLoader, but only on first usage, allowing to keep its parent classes in the bootstrap.php.cache file as done previously.

the nice side-effect is also making it simpler to use AppCache as it is now autoloaded

**Comment by Tobion** [comment]
Thank you @stof.

**Comment by JHGitty** [comment]
This fix is not included if I create a new project with the symfony installer tool.
```bash
# Linux, Mac OS X
$ symfony new test

# Windows
c:\> php symfony new test
```

I think a lot of people (for example beginners) will not know this issue.

**Comment by stof** [comment]
@JHGitty this is expected, as this has been merged *after* the 2.8 release, and so will be available in the 2.8.1 archives

**Comment by xabbuh** [comment]
It it isn't too much work it would nonetheless be good to rebuild the archives with the current SE to reduce bad experiences for anyone starting new projects based on 2.8.0 or 3.0.0 in the meantime.

**Comment by jvasseur** [comment]
@xabbuh that would mean recreating the tags which is probably a bad idea.

**Comment by javiereguiluz** [comment]
Besides, even for small changes, recreating the published packages is scary because unexpected things could break.

**Comment by JHGitty** [comment]
That because I hope there will be a new release (2.8.1, 3.0.1, ..) as soon as possible :+1:

**Comment by Pierstoval** [comment]
As I asked on twitter, a new patch version is released approximately every month, so we can expect 2.8.1 to be released in less than 20 days :+1: :wink:

**Pull request merged**
