### PR TITLE
Changed ORM default naming strategy to underscore

### PR DESCRIPTION
**Pull request by hason**
This PR partially fixes the problem with case-sensitive identifiers http://dev.mysql.com/doc/refman/5.0/en/identifier-case-sensitivity.html

Replaces https://github.com/doctrine/DoctrineBundle/pull/406

### CODE REVIEW

**Comment by Pierstoval** [comment]
I think that this can be very useful :+1:

**Comment by hacfi** [comment]
:+1:

**Comment by TomasVotruba** [comment]
:+1:

**Comment by stof** [comment]
:+1: The default value cannot be changed in DoctrineBundle because it would be a BC break for existing projects, but the underscore is a much saner choice than the default naming strategy keeping camel-cased names. It has much less compatibility issues across platforms.

**Comment by fabpot** [comment]
Thank you @hason.

**Comment by weaverryan** [comment]
:+1: Wish we had done this awhile ago :)

**Comment by stof** [comment]
@weaverryan better late than never

**Pull request merged**
