### PR TITLE
csrf_protection is now under framework.form instead of framework

### PR DESCRIPTION
**Pull request by BenoitLeveque**
Unrecognized option "csrf_protection" under "framework" was triggered when installing master version of this repository

### CODE REVIEW

**Comment by Tobion** [comment]
:+1:  Needs to be merged in 2.7

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @BenoitLeveque.

**Comment by WouterJ** [comment]
This should be reverted @fabpot

**Comment by fabpot** [comment]
reverted

**Pull request closed without merging**
