### PR TITLE
update Doctrine Configuration in config.yml

### PR DESCRIPTION
**Pull request by ykseiljon**
allow to use other database driver from parameters.yml

### CODE REVIEW

**Comment by ogizanagi** [comment]
The `%database_driver%` does not exist in `app/config/parameters.yml.dist`

**Comment by ykseiljon** [comment]
I updated app/config/parameters.yml, then i need to change config.yml to connect to other database driver and worked well.
If I use assistant to configure database connection it show that parameter (database_driver on app/config/parameters.yml).

**Comment by ogizanagi** [comment]
The issue is that you updated the app configuration to use the `database_driver`, but you didn't edit the `parameters.yml.dist` file from this repository within your PR. 
`parameters.yml.dist` file which is used by the Composer Incenteev parameter handler to ask the user the parameters values after a `composer install`.

Doing a fresh install of symfony standard edition will then fail, because of that missing parameter from the `.dist` file. The `database_driver` parameter will never be created in `parameters.yml`.

Also, the `database_driver` used to exists, but has been removed. (See above referenced PRs for more informations about that)

**Comment by ykseiljon** [comment]
thanks, after check it i understand reason, it work good if i write driver of appropriate database in config.yml

**Comment by Pierstoval** [comment]
IIRC, the `database_driver` was removed from `parameters.yml` because it's mostly a "project-related" parameter, not a "platform-related". 
 
Everything in the `parameters.yml` should depend only on the platform in which you deploy/dev/test your app, and the rest should stay in `config.yml`, this is why this parameter was removed from the dist file.

**Comment by xabbuh** [comment]
@Pierstoval is right. That's the reason why the parameter was removed in #776 (see https://github.com/symfony/symfony-standard/pull/776#discussion_r23593282). Therefore I'm going to close here.

**Comment by ykseiljon** [comment]
I get it.  But I think is necessary to update configuration assistant, because it still write database_driver in parameter.yml. Thanks for answer.

**Comment by xabbuh** [comment]
Did you experience that behaviour with a freshly installed Symfony application?

**Comment by Pierstoval** [comment]
@xabbuh I've tested on a freshly installed 2.7 version and actually, the `SensioDistribution:Configurator` controller adds the `database_driver` to `parameters.yml`.
 
I didn't use this component for months, but actually, it also generates a completely inline parameters.yml file. I'm on MacOSX10.10.

**Comment by ykseiljon** [comment]
@xabbuh, @Pierstoval is right. And I appreciate the explanations of the change reasons and understood. It's sense to me too.

**Comment by Pierstoval** [comment]
The issue is then related to `SensioDistributionBundle`, I think we can close it here

**Comment by xabbuh** [comment]
see sensiolabs/SensioDistributionBundle#219

**Pull request closed without merging**
