### PR TITLE
Removed beta flag from release version

### PR DESCRIPTION
**Pull request by maschmann**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The lock file needs updating too doesn't it?

**Comment by maschmann** [comment]
Absolutely right. Will do.

**Comment by xabbuh** [comment]
:+1:

**Comment by Tobion** [comment]
:+1:

**Comment by aitboudad** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @maschmann.

**Pull request closed without merging**
