### PR TITLE
DefaultController extends the new AbstractController

### PR DESCRIPTION
**Pull request by vudaltsov**

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @vudaltsov.

**Comment by fabpot** [comment]
Reverted as this has not been tested. Code is broken (`getParameter()` is not available in AbstractController).

**Comment by vudaltsov** [comment]
Yes, my fault to have not taken this into account.

**Comment by dunglas** [comment]
This patch is present in the last tagged version, it means that when you run `symfony new my-project` you get a red error instead of the default page. Can you tag a new version?

**Pull request merged**
