### PR TITLE
Use a proper version constraint

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Any reason why this wasn't used already? I noticed this when looking at https://github.com/symfony/symfony-standard/pull/850.

### CODE REVIEW

**Comment by gnugat** [comment]
You could push it a little bit further: `^2.8.0@dev`

**Comment by mickaelandrieu** [comment]
humm, should be also done for Symfony3

**Comment by GrahamCampbell** [comment]
> You could push it a little bit further: ^2.8.0@dev

:-1: because all other branches are like `2.7.*`.

**Comment by GrahamCampbell** [comment]
`^2.8.0@dev` - that's wrong anyway, because it would include 2.9+ too. Yes, I know 2.8 is the last 2.x minor release, but that version constraint would be wrong, semantically.

**Comment by GrahamCampbell** [comment]
Ping @fabpot. :)

**Comment by Tobion** [comment]
Thank you @GrahamCampbell.

**Comment by GrahamCampbell** [comment]
:)

**Pull request merged**
