### PR TITLE
Register WebServerBundle in prod env

### PR DESCRIPTION
**Pull request by maidmaid**
This also allows to run project in prod env, that is usefull to check prod config for example.

```
php bin/console -e prod server:*
```

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
How do you check prod config with PHP built-in web server?

**Comment by ghost** [comment]
Why would you run this bundle in a production environment? I'd against this pull request.

**Comment by maidmaid** [comment]
In development phase, I sometimes run locally ``php bin/console server:start -e prod`` to check the production things like doctrine cache, monolog handlers or payment configuration. Before 3.3, it was possible to do it *by default*.

**Comment by chalasr** [comment]
I think that's a good thing it is not anymore, the webserver is not meant to ensure that your application runs fine. If you use it for that you can enable it on your side, but that should not be a generalised practice IMO

**Comment by fabpot** [comment]
Keep in mind that this is just the default. Feel free to change it, but default should be about the best practice.

**Pull request closed without merging**
