### PR TITLE
Sort Composer packages automatically

### PR DESCRIPTION
**Pull request by javiereguiluz**
I do this in all my projects and Laravel added this too recently (https://github.com/laravel/framework/pull/16843) but I don't know if others will agree 😄

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
In this case, I think you have to reorder existing packages as well in this PR.

**Comment by HeahDude** [comment]
👍

**Comment by dunglas** [comment]
👍

**Comment by bocharsky-bw** [comment]
What about to sort registered bundles in `AppKernel.php` in addition to this suggestion?
P.S. I'm not sure this idea worth to be opened in another issue.

**Comment by lyrixx** [comment]
:+1:

**Comment by fabpot** [comment]
How does that work? I've just added this config to my composer.json, but running composer install or composer update does not sort my composer.json deps.

**Comment by chalasr** [comment]
@fabpot indeed, running `install` or `update` doesn't seem to trigger it but `require` does.

**Comment by fabpot** [comment]
@chalasr Ok, sounds a bit counter-intuitive. I would have expected `update` to reorder my deps as well.

**Comment by chalasr** [comment]
I agree, that could deserve a PR on composer.

**Comment by stof** [comment]
@fabpot ``composer update`` is not allowed to alter the composer.json file (and ``composer install`` is not even allowed to alter the lock file)

**Comment by fabpot** [comment]
I've done that as of 2.7 and merged everything up.

**Pull request closed without merging**
