### PR TITLE
ordered use statements

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by OskarStark** [comment]
any news here?

**Review by jakzal — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
But for 2.7?

**Comment by OskarStark** [comment]
yes, 2.7 is right, shall i change the PR or can you apply it against 2.7 @xabbuh ?

**Comment by jakzal** [comment]
@OskarStark I think we'll be able to merge it to 2.7. Thanks!

**Comment by OskarStark** [comment]
any news here or work todo?

**Review by Pierstoval — APPROVED** [review]

**Review by julienfalque — APPROVED** [review]

**Review by lyrixx — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by OskarStark** [comment]
Shall I close the PR?

**Review by bocharsky-bw — APPROVED** [review]

**Comment by OskarStark** [comment]
No merge until now, I close here 😢

**Pull request closed without merging**
