### PR TITLE
Removed any reference to the web configurator

### PR DESCRIPTION
**Pull request by javiereguiluz**
We're trying to remove the web configurator in:  https://github.com/sensiolabs/SensioDistributionBundle/pull/217

For that PR to be merged, we need to remove any reference to the configurator.

### CODE REVIEW

**Comment by Pierstoval** [comment]
Isn't the `config.php` file generated by `SensioDistributionBundle`?

**Comment by javiereguiluz** [comment]
@Pierstoval I can't find any code in SensioDistributionBundle related to this and the `web/config.php` file already exists in this repository.

**Comment by Pierstoval** [comment]
And what about [Resources/skeleton/web/config.php](https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/skeleton/web/config.php)?

**Comment by javiereguiluz** [comment]
Correct! I'll investigate this file a bit more. Thanks.

**Comment by stof** [comment]
@javiereguiluz any change to this file should be done in SensioDistributionBundle. There is a composer hook updating the file in the project when updating the bundle.

**Comment by javiereguiluz** [comment]
@Pierstoval thanks for reporting this issue and @stof thanks for confirming it. I've moved these changes to where they belong: https://github.com/sensiolabs/SensioDistributionBundle/pull/217 so I'm closing this pull request. Thanks!

**Pull request closed without merging**
