### PR TITLE
Run $kernel->terminate after connection is closed in HHVM

### PR DESCRIPTION
**Pull request by lmcd**
In php-fpm, we can run cleanup code/blocking tasks after the HTTP connection is closed with `fastcgi_finish_request`. HHVM doesn't have this function, but it does have the counterpart `register_postsend_function`.

See here:
https://github.com/facebook/hhvm/blob/master/hphp/doc/extension.new_functions
https://github.com/facebook/hhvm/issues/1230

Note: haven't tested yet. Just putting it out there.

### CODE REVIEW

**Comment by allan-simon** [comment]
Hello, how can one test this ?

**Comment by alesblaznik** [comment]
@lmcd I've tested it just now on HipHop VM 3.6.2 (rel) and it works as expected - not any issues so far.

@fabpot Should this be added to Symfony standard since a lot of folks are starting use HHVM nowadays and actually it took me a while to recognize that fast_cgi_request_finish don't work on hhvm? Maybe for now it could be enought that this lines should be commented and say "uncomment this, if you're using hhvm"

**Comment by fabpot** [comment]
If the code works, let's see where this should be added in Symfony itself.

**Comment by hacfi** [comment]
We could close this!? If it’s really missing someone will notice, test it and this can be merged.

**Comment by fabpot** [comment]
As HHVM is not a priority for the core team, nobody is using it (we even discussed removing its official support in Symfony), someone using HHVM should finish this change so that we can merge it. In any case, it cannot be merge as is as this should be part of Symfony, not the standard edition.

**Comment by fabpot** [comment]
Closing this one as apparently nobody has the issue... or nobody uses HHVM and Symfony.

**Pull request closed without merging**
