### PR TITLE
SensioGeneratorBundle not found for composer install --no-dev

### PR DESCRIPTION
**Pull request by marius-rizac**
When running `composer install --no-dev` or `composer update --no-dev` this error is shown 
PHP Fatal error:  Class "Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle" not found in ...app/AppKernel.php on line 25
because `sensio/generator-bundle` is a development dependency.

### CODE REVIEW

**Comment by xabbuh** [comment]
The SensioGeneratorBundle is only loaded in the application kernel if you run it in the `dev` environment. And if you access the application in the `dev` environment, you should have installed the dev dependencies too.

**Comment by marius-rizac** [comment]
@xabbuh please run `composer install --no-dev` on a new cloned directory. And when you run composer install, which environment is used ?

**Comment by bocharsky-bw** [comment]
@marius-rizac By default used `dev` environment. Composer does not share environment with Symfony. You can change it with `export SYMFONY_ENV=prod`. Check http://symfony.com/doc/current/cookbook/deployment/tools.html#c-install-update-your-vendors for more info.

**Comment by Pierstoval** [comment]
+1 for @xabbuh and @bocharsky-bw, and I'll add that if you install with `--no-dev` you might be using a production machine so you should export the env var directly to your machine's environment.

**Comment by marius-rizac** [comment]
@bocharsky-bw ok, got it. thanks.

**Pull request closed without merging**
