### PR TITLE
Very minor code style fix

### PR DESCRIPTION
**Pull request by tomat**

### CODE REVIEW

**Comment by Pierstoval** [comment]
This file is generated by [SensioDistributionBundle](https://github.com/sensiolabs/SensioDistributionBundle), you should close this PR and open a new one for [this file](https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/skeleton/app/check.php) on

**Comment by tomat** [comment]
Thanks

**Comment by tomat** [comment]
Was already fixed, just not in a release yet :-)

**Comment by Pierstoval** [comment]
Great then :+1: 
Will be available in the next release maybe

**Pull request closed without merging**
