### PR TITLE
Default system cache is APCu

### PR DESCRIPTION
**Pull request by nicolas-grekas**

### CODE REVIEW

**Comment by xabbuh** [comment]
👍

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by JHGitty** [comment]
Why is this only merged to `3.1` and not to `master` ?

**Comment by Pierstoval** [comment]
I think that's because it adds a new dependency?

**Comment by JHGitty** [comment]
But why should new dependencies not be added to master? Shouldn't it be added to new versions like 3.2?

**Comment by stof** [comment]
@JHGitty this is the other way actually. Older branches are merged into newer branches on a regular basis. So if it is merged into 3.1, it will also be available in 3.2 soon.
If it had been merged into master directly, 3.1 would never contain this change.

**Comment by JHGitty** [comment]
Okay, great. Thanks! :+1:

**Pull request merged**
