### PR TITLE
License year range updated

### PR DESCRIPTION
**Pull request by romqin**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none
| License       | MIT
| Doc PR        | none

Happy new year !

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by Tobion** [comment]
:+1:

**Comment by gnugat** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @romqin.

**Pull request merged**
