### PR TITLE
Require bootstrap instead of autoload

### PR DESCRIPTION
**Pull request by Koc**

### CODE REVIEW

**Comment by Pierstoval** [comment]
I don't think autoload would have been thrown out of bootstrap in 7311e70 to be reintroduced later :confused:

**Comment by Koc** [comment]
But the first lines of generated bootstrap is:

```php
namespace {
    error_reporting(error_reporting() & ~E_USER_DEPRECATED);
    $loader = require_once __DIR__.'/./autoload.php';
}
```

so it includes autoload.

//cc @Tobion

**Comment by Tobion** [comment]
https://github.com/sensiolabs/SensioDistributionBundle/blob/master/UPGRADE.md#upgrade-from-40-to-50

**Comment by Koc** [comment]
Thank you @Tobion

**Pull request closed without merging**
