### PR TITLE
moved back dep binaries into vendor/dir

### PR DESCRIPTION
**Pull request by fabpot**
Move back all binaries from deps in `vendor/dir`, it's more standard amongst PHP projects using Composer.

### CODE REVIEW

**Comment by gnugat** [comment]
Not to mention that it allows developers to create their own scripts in the `bin` folder, now that it is no longer ignored.

**Comment by WouterJ** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Comment by hacfi** [comment]
:+1:

**Comment by weaverryan** [comment]
:+1: And I think going into `master` is correct - it'll cause issues with documentation (hey, why do I get command not found when running `bin/XXXX`?) and I think doing it in 3.0 will help that a lot.

**Comment by Pierstoval** [comment]
:+1: too, it's a bit confusing to have first "app/console", then "bin/console", but afterwards having console in the same dir as doctrine, because we never use doctrine "manually" , so a single sir for all vendor bin is great !

**Pull request merged**
