### PR TITLE
Fix "!event" deprecation

### PR DESCRIPTION
**Pull request by dunglas**

### CODE REVIEW

**Comment by stof** [comment]
I would use single quotes. Single-quoted YAML scalars are simpler, because there are no special chars inside them (except the single quote itself)

**Comment by dunglas** [comment]
@stof done (I've also replaced all existing double quotes by single quotes for the sake of consistency).

**Comment by fabpot** [comment]
Shouldn't this be done in 2.7 instead?

**Comment by dunglas** [comment]
Why not, but the deprecation is triggered only since 3.3.

**Comment by stof** [comment]
Replacing existing quotes should indeed be done in 2.7, to make merging branches easier

**Comment by dunglas** [comment]
* Switched to 2.7
* Uniformized indentation (no align)
* Unifomized comments

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request merged**
