### PR TITLE
Adding docker-compose support

### PR DESCRIPTION
**Pull request by rawkode**

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Probably it's more appropriable for Symfony Demo app?

**Comment by bocharsky-bw** [comment]
It took ~1.5s to generate welcome page 😥 Is there a way to speed up it?

screen shot 2016-10-08 at 21 04 09

**Comment by rawkode** [comment]
I'll assume you're on OSX. Running Docker for Mac currently uses osxfs, which has known performance issues atm

**Comment by bocharsky-bw** [comment]
Yes, I'm on Mac. Ah, I hoped that "native" OS X Docker solution would improve performance but seems it didn't happen :(

**Comment by gmsantos** [comment]
@bocharsky-bw try this http://docker-sync.io/, a colleague told me that works well

**Comment by bocharsky-bw** [comment]
Hm, it's something new and mystery to me, but wow, looks like it rocks! It's a bit confusing me, but I found a working solution: https://github.com/timglabisch/symfony_docker_sync and it super fast - only *65ms*! I definitely want to dig deeper. Thank you @gmsantos a lot!!

**Comment by jakzal** [comment]
:-1: for similar reasons given in https://github.com/symfony/symfony-standard/issues/992#issuecomment-247942783 and https://github.com/symfony/symfony/issues/18377#issuecomment-204329546 

Instead, we could add a cookbook to the docs with an example configuration (or add it to the demo app as @bocharsky-bw suggests).

**Comment by bocharsky-bw** [comment]
I think it'd be nice to have some official good example in docs for Docker: a related issue on docs here https://github.com/symfony/symfony-docs/issues/4055 .

**Pull request closed without merging**
