### PR TITLE
Changed Symfony2 occurrences to Symfony 3.

### PR DESCRIPTION
**Pull request by hhamon**

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I suggest renaming to just `Symfony`, without any version number

**Comment by bocharsky-bw** [comment]
Duplicate of https://github.com/symfony/symfony-standard/pull/903

**Comment by hhamon** [comment]
I've renamed to just Symfony. Feel free to close it or merge it depending on the duplicate.

**Comment by Pierstoval** [comment]
@hhamon Only `README.md` should be updated. The `symfony_requirements` file will be updated on the next symfony-standard release automatically when @fabpot will update dependencies for the standard edition, so there's no need in updating it manually as it comes from [SensioDistributionBundle](https://github.com/sensiolabs/SensioDistributionBundle).

**Comment by Tobion** [comment]
as @Pierstoval said, please only update the readme

**Comment by Tobion** [comment]
Done in 2.3 as this is also where requirements etc will only use `Symfony`.

**Pull request closed without merging**
